version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: production
    command: ["node", "server.js"]
    hostname: frontend
    network_mode: "host"
    restart: unless-stopped
