version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: production
    command: ["node", "server.js"]
    hostname: frontend
    networks:
      app_network:
        ipv4_address: 172.17.0.10 # Assign the container an IP address in the same subnet

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.0.0/16 # Define the subnet for your network
          gateway: 172.17.0.1 # Set the gateway to 172.17.0.1
